_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: "/home/zyserver/disk1/hmx/SwinTextSpotter-main/output_weight_recbackbone_mixtrain_12W/model_final.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("vintext_train","vintext_val")
  TEST:  ("vintext_test",)
SOLVER:
  STEPS: (60000,90000)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
  INFERENCE_TH_TEST: 0.4
INPUT:
  FORMAT: "RGB"
OUTPUT_DIR: "output_weight_recbackbone_mixtrain_vintext/"