_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: "/data/hmx/SwinTextSpotterv2/output_weight_recbackbone_mixtrain_26W_2_wihout_hiertext/model_final.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
  REC_HEAD:
      # POOLER_RESOLUTION: (16,48)
      # RESOLUTION: (32, 96)
      BATCH_SIZE: 32
INPUT:
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1824
DATASETS:
  TRAIN: ("ctw_1500",)
  TEST:  ("ctw1500_test",)
SOLVER:
  STEPS: (60000,90000)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"
OUTPUT_DIR: "output_weight_recbackbone_mixtrain_26W_2_wihout_hiertext_ctw1500_10w"
